### ISSUE TITLE
How do I get the position of HMD in real time

### ISSUE THREAD

**Issue by fchen09** [gpsnmeajp/VirtualMotionTracker#6]
こんにちは、素晴らしいソフトウェアをありがとう。
どうすればHMDの位置をリアルタイムで取得できるのか気になる
ドライバーからHMDの位置を取得できると便利です。
ありがとうございました。

Hi, Thanks for your wonderful software.
I am wondering how I can get the position of HMD in real-time
If I can get the HMD position from the driver, it will be convenient.
Thank you.

**Comment by gpsnmeajp** [comment]
This is not a bug.

**Comment by gpsnmeajp** [comment]
Obtaining the HMD's position is not supported as it is not the purpose of this driver.
Please modify it yourself or find a fork.

**Comment by gpsnmeajp** [comment]
If you just want the HMD position, use the SteamVR/OpenVR API.

**Comment by fchen09** [comment]
Thank you!
Sorry for the wrong label.
