### ISSUE TITLE
SteamVR cannot load out of VMT

### ISSUE THREAD

**Issue by nicocrayer** [gpsnmeajp/VirtualMotionTracker#7]
steamvr は vmt を読み込めません
SteamVR cannot load out of VMT
When I click uninstall, the vmt cannot be installed again, steamVR does not recognize, how to solve it？thanks
私がアンインストールをクリックすると、VMTは再びインストールすることはできませんし、steamvrは、どのように解決するかを認識しません
![FLIIC6(}TE 8JNVP4VI5$V8](https://user-images.githubusercontent.com/76022203/201639781-50fb8e4b-0872-46b8-bd26-60158c8f8ece.png)

**Comment by gpsnmeajp** [comment]
Please uninstall Steam VR completely, delete the SteamVR configuration file (steamvr.vrsettings) completely and restart your PC.
Then try again instration.
There is nothing more I can do for you.
