### ISSUE TITLE
PC side VR view is not displayed

### ISSUE THREAD

**Issue by oneday1992** [gpsnmeajp/VirtualMotionTracker#8]
日本語で書いてください。自信がない場合は、英文と、機械翻訳を添えてください。  
Please write in Japanese language. If you are not confident, please include English and machine translation.

**バグの説明**
どのようなものかを説明してください

PC側のVRビューは表示されない
trackingoverridesを使用してオーバーレイを配置すると、VRビューは表示されず、部屋の設定が必要だというメッセージが表示されます（C 200）。私は基地局には向いていません。

When I use trackingoverrides to locate overrides, the VR view does not display and prompts me to need room settings（C200）. I don't apply to base stations.

**再現手順**
バグの再現手順:

サードパーティのポジショニング データを受信するトラッカーを作成しました. steamvr.settings ファイルに次の内容を追加し、トラッカーのポジショニングがヘッドセットのポジショニングをカバーしたところ、VR ヘッドセットではすべてが正常でしたが、 PC 側の steamvr アプリケーション:
部屋のセットアップ
部屋のセットアップを実行して、プレイ エリアとシャペロンの境界を定義してください。(C200)
次に、この vr ビューには何もありません。

I created a tracker to receive third-party positioning data. I added the following content to the steamvr.settings file, and the tracker positioning covered the headset positioning, and then everything was normal in the VR headset, but a prompt popped up in the steamvr application on the PC side:

Room Setup
Please perform Room Setup to define your play area and chaperone bounds.(C200)

Then this vr view has nothing.

**期待する動作**
どんな動作を期待しているのかを記載してください
vrビューが正常に表示されることを期待しています。
I expect the vr view to display normally.

**Comment by gpsnmeajp** [comment]
It looks like modded icon.
I won't answer any questions for modded VMT.

If you want to continue,

+ Please run room setup as directed. 
+ Please download and run original binary.
+ Please provide repro code.
+ Please provide your SteamVR system report.
